---
title: "Saving Results"
author: "Kozo Nishida, Kristina Hanspers and Alex Pico"
date: "`r Sys.Date()`"
output:
  BiocStyle::html_document:
    toc: true
    toc_depth: 4
    df_print: paged
---
```{r, echo = FALSE}
knitr::opts_chunk$set(
  eval=FALSE
)
```

*The R markdown is available from the pulldown menu for* Code *at the upper-right, choose "Download Rmd", or [download the Rmd from GitHub](https://raw.githubusercontent.com/nrnb/gsod2019_kozo_nishida/master/saving-results.Rmd).*

<hr />

Cytoscape provides a number of ways to save results and visualizations:

<hr />

# Installation
```{r, eval = FALSE}
if (!requireNamespace("BiocManager", quietly = TRUE))
  install.packages("BiocManager")
if(!"RCy3" %in% installed.packages())
  BiocManager::install("RCy3")
library(RCy3)
```

# Saving results

- As a session:

```
saveSession('./saving-results')
```

- As an image:

```
exportImage('./saving-results', 'PDF')
exportImage('./saving-results', 'PNG')
exportImage('./saving-results', 'JPEG')
exportImage('./saving-results', 'SVG')
exportImage('./saving-results', 'PS')
```

- To the web:

```
exportNetworkToNDEx("user", "pass", TRUE)
```

- As a graph format file:

```
exportNetwork('./saving-results', 'CX')
exportNetwork('./saving-results', 'cyjs')
exportNetwork('./saving-results', 'graphML')
exportNetwork('./saving-results', 'xGMML')
exportNetwork('./saving-results', 'SIF')
```
